# Generated by Django 3.0.5 on 2020-05-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200520_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sign_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
