# Generated by Django 3.0.5 on 2020-05-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_project_sign_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
