# Generated by Django 3.0.5 on 2020-05-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200522_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tax',
            field=models.IntegerField(blank=True, default=0.0825, editable=False, null=True),
        ),
    ]
