# Generated by Django 3.0.5 on 2020-05-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_project_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tax',
            field=models.IntegerField(blank=True, default=0.0825, null=True),
        ),
    ]
