# Generated by Django 3.0.5 on 2020-05-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200522_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tax',
            field=models.FloatField(blank=True, default=0.0825, null=True),
        ),
    ]
