# Generated by Django 3.0.5 on 2020-05-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200524_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tax_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
